language: ruby
before_install: gem install bundler
script: bundle exec rake spec
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
matrix:
  exclude:
    # remove ree from jdk matrix
    - rvm: ree
      jdk: openjdk6
    - rvm: ree
      jdk: openjdk7
    - rvm: ree
      jdk: oraclejdk7

    # remove 1.8.7 from jdk matrix
    - rvm: 1.8.7
      jdk: openjdk6
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: 1.8.7
      jdk: oraclejdk7

    # remove 1.9.2 from jdk matrix
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7

    # remove 1.9.3 from jdk matrix
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7

    # remove ruby-head from jdk matrix
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7

    # remove rbx-18mode from jdk matrix
    - rvm: rbx-18mode
      jdk: openjdk6
    - rvm: rbx-18mode
      jdk: openjdk7
    - rvm: rbx-18mode
      jdk: oraclejdk7

    # remove rbx-19mode from jdk matrix
    - rvm: rbx-19mode
      jdk: openjdk6
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: oraclejdk7

    # remove jruby-18mode, jruby-19mode and jruby-head from non-jdk matrix
    - rvm: jruby-18mode
      jdk:
    - rvm: jruby-19mode
      jdk:
    - rvm: jruby-head
      jdk:
notifications:
  email:
    - mbj@seonic.net
